const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"领导管理",
			            "menuJump":"列表",
			            "tableName":"lingdao"
			        }
			    ],
			    "menu":"领导管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"科室职员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"科室职员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"库房管理",
			            "menuJump":"列表",
			            "tableName":"kufang"
			        }
			    ],
			    "menu":"库房管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "报表",
			                "删除"
			            ],
			            "menu":"设备管理",
			            "menuJump":"列表",
			            "tableName":"shebei"
			        }
			    ],
			    "menu":"设备管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"设备出入库房管理",
			            "menuJump":"列表",
			            "tableName":"shebeichuruku"
			        }
			    ],
			    "menu":"设备出入库房管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"设备转科管理",
			            "menuJump":"列表",
			            "tableName":"shebeizhuanke"
			        }
			    ],
			    "menu":"设备转科管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"设备报损管理",
			            "menuJump":"列表",
			            "tableName":"shebiebaosun"
			        }
			    ],
			    "menu":"设备报损管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"质量检测登记管理",
			            "menuJump":"列表",
			            "tableName":"shebiejiance"
			        }
			    ],
			    "menu":"质量检测登记管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"设备维修管理",
			            "menuJump":"列表",
			            "tableName":"shebieweixiu"
			        }
			    ],
			    "menu":"设备维修管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"设备采购管理",
			            "menuJump":"列表",
			            "tableName":"caigoujihua"
			        }
			    ],
			    "menu":"设备采购管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"科室管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryKeshi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"库房类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryKufang"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"设备类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryShebei"
			        }
			    ],
			    "menu":"基础数据管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告资讯管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告资讯管理"
            }
            /*,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"数据备份",
			            "menuJump":"列表",
			            "tableName":"beifen"
			        },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"数据还原",
					    "menuJump":"列表",
					    "tableName":"huanyuan"
					}
			    ],
			    "menu":"数据库管理"
			}*/
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"科室职员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"科室职员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"库房管理",
			            "menuJump":"列表",
			            "tableName":"kufang"
			        }
			    ],
			    "menu":"库房管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"设备管理",
			            "menuJump":"列表",
			            "tableName":"shebei"
			        }
			    ],
			    "menu":"设备管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			            ],
			            "menu":"设备出入库房管理",
			            "menuJump":"列表",
			            "tableName":"shebeichuruku"
			        }
			    ],
			    "menu":"设备出入库房管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			            ],
			            "menu":"设备转科管理",
			            "menuJump":"列表",
			            "tableName":"shebeizhuanke"
			        }
			    ],
			    "menu":"设备转科管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			            ],
			            "menu":"设备报损管理",
			            "menuJump":"列表",
			            "tableName":"shebiebaosun"
			        }
			    ],
			    "menu":"设备报损管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			            ],
			            "menu":"质量检测登记管理",
			            "menuJump":"列表",
			            "tableName":"shebiejiance"
			        }
			    ],
			    "menu":"质量检测登记管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			            ],
			            "menu":"设备维修管理",
			            "menuJump":"列表",
			            "tableName":"shebieweixiu"
			        }
			    ],
			    "menu":"设备维修管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			            ],
			            "menu":"设备采购管理",
			            "menuJump":"列表",
			            "tableName":"caigoujihua"
			        }
			    ],
			    "menu":"设备采购管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告资讯管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告资讯管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"领导",
	    "tableName":"lingdao"
	},
	{
	        "backMenu":[
	            {
				    "child":[
				        {
				            "buttons":[
				                "查看"
				            ],
				            "menu":"领导管理",
				            "menuJump":"列表",
				            "tableName":"lingdao"
				        }
				    ],
				    "menu":"领导管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看"
				            ],
				            "menu":"库房管理",
				            "menuJump":"列表",
				            "tableName":"kufang"
				        }
				    ],
				    "menu":"库房管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看"
				            ],
				            "menu":"设备管理",
				            "menuJump":"列表",
				            "tableName":"shebei"
				        }
				    ],
				    "menu":"设备管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看",
				                "新增",
				                "删除"
				            ],
				            "menu":"设备出入库房管理",
				            "menuJump":"列表",
				            "tableName":"shebeichuruku"
				        }
				    ],
				    "menu":"设备出入库房管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看",
				                "新增",
				                "删除"
				            ],
				            "menu":"设备转科管理",
				            "menuJump":"列表",
				            "tableName":"shebeizhuanke"
				        }
				    ],
				    "menu":"设备转科管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看",
				                "新增",
				                "删除"
				            ],
				            "menu":"设备报损管理",
				            "menuJump":"列表",
				            "tableName":"shebiebaosun"
				        }
				    ],
				    "menu":"设备报损管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看",
				                "新增",
				                "删除"
				            ],
				            "menu":"质量检测登记管理",
				            "menuJump":"列表",
				            "tableName":"shebiejiance"
				        }
				    ],
				    "menu":"质量检测登记管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看",
				                "新增",
				                "删除"
				            ],
				            "menu":"设备维修管理",
				            "menuJump":"列表",
				            "tableName":"shebieweixiu"
				        }
				    ],
				    "menu":"设备维修管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看",
				                "新增",
				                "删除"
				            ],
				            "menu":"设备采购管理",
				            "menuJump":"列表",
				            "tableName":"caigoujihua"
				        }
				    ],
				    "menu":"设备采购管理"
				}
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"公告资讯管理",
	                        "menuJump":"列表",
	                        "tableName":"news"
	                    }
	                ],
	                "menu":"公告资讯管理"
	            }
	        ],
	        "frontMenu":[],
	        "hasBackLogin":"是",
	        "hasBackRegister":"否",
	        "hasFrontLogin":"否",
	        "hasFrontRegister":"否",
	        "roleName":"科室职员",
	        "tableName":"yonghu"
	    }
]
    }
}
export default menu;
